version: '3'
services:
  react-app:
    build:
      context: .                                                                    # Current directory
      dockerfile: Dockerfile                                                        # Dockerfile name
    ports:
      - "3000:3000"                                                                 # Port mapping - host:container
    volumes:
      - .:/app                                                                      # Volume mapping - host:container
    environment:
      - CHOKIDAR_USEPOLLING=true                                                    # Required for live reloading 

  web-server:                                                                       # Nginx web server
    image: nginx:alpine                                                             # Nginx image
    ports:
      - "80:80"                                                                     # Port mapping - host:container
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf                                          # Custom Nginx configuration
    depends_on:
      - react-app                                                                   # Wait for react-app to start
